// Generated by Xata Codegen 0.29.3. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "userProfile",
    columns: [
      { name: "userId", type: "string", unique: true },
      { name: "username", type: "string", unique: true },
      { name: "name", type: "string" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type UserProfile = InferredTypes["userProfile"];
export type UserProfileRecord = UserProfile & XataRecord;

export type DatabaseSchema = {
  userProfile: UserProfileRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://learn-with-joseph-75l2bu.us-east-1.xata.sh/db/kindeauth",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient();
  return instance;
};
